export const programmingLanguages = [
    {value: 'JavaScript', label: 'JavaScript'},
    {value: 'TypeScript', label: 'TypeScript'},
    {value: 'Python', label: 'Python'},
    {value: 'Go', label: 'Go'},
    {value: 'C', label: 'C'},
    {value: 'C++', label: 'C++'},
    {value: 'Java', label: 'Java'},
    {value: 'dotnet', label: 'C#'},
    {value: 'PHP', label: 'PHP'},
    {value: 'Ruby', label: 'Ruby'},
    {value: 'Swift', label: 'Swift'},
    {value: 'SwiftUI', label: 'SwiftUI'},
    {value: 'Kotlin', label: 'Kotlin'},
    {value: 'Scala', label: 'Scala'},
    {value: 'Rust', label: 'Rust'},
    {value: 'Haskell', label: 'Haskell'},
    {value: 'Groovy', label: 'Groovy'},
    {value: 'Fortran', label: 'Fortran'},
    {value: 'COBOL', label: 'COBOL'},
];