import type {AppProps} from 'next/app'
import {ChakraProvider} from "@chakra-ui/react";
import Head from "next/head";
import theme from "@/theme/theme";

export default function App({Component, pageProps}: AppProps) {
    return (
        <ChakraProvider theme={theme}>
            <Head>
                <title>Test Automation Buddy</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/test-automation.png"/>
            </Head>
            <Component {...pageProps}/>
        </ChakraProvider>
    )
}
